#!/bin/bash

cd `dirname $0`
MYDIR=`pwd`

# Only Pi4 supported today
PIVERSION=4

CONFIG=$1
if [ "$CONFIG" == "" ]; then
  CONFIG="default"
fi
if [ "$CONFIG" == "4" ]; then
 echo "Do not use Pi version, it is fixed to 4"
 exit 1
fi

if [ "$BRSRCDIR" == "" ]; then
  BRSRCDIR=buildroot
fi

BRDIR=`./brdir $PIVERSION`
echo "Configuring in $BRDIR"
cd `dirname $0`
cd $BRSRCDIR
echo "Using $MYDIR/configs/pi$PIVERSION-$CONFIG.config"
cp $MYDIR/configs/pi$PIVERSION-$CONFIG.config $BRDIR/.config
make O=$BRDIR BR2_EXTERNAL=../brext menuconfig
cp $BRDIR/.config $MYDIR/configs/pi$PIVERSION-$CONFIG.config
