#!/bin/bash
cd `dirname $0`

VERSION=4
HOST=$1
if  [ "$HOST" == "" ]; then
 echo $0 hostname
 echo  e.g. $0 10.0.1.23 will push the current release to the Pi with the IP address 10.0.1.23
 exit 1
fi 

PORT=22

if [ "$PASSWORD" == "" ]; then
  PASSWORD=pinball
fi

REMOTEVERSION=""

if [ "$REMOTEVERSION" == "" -o "$REMOTEVERSION" == "$VERSION" ]; then

 echo "Packaging Pi$VERSION release"
 ./compile $VERSION pp-updater
 ./create-updater $VERSION

 echo "Copying software to $HOST"
 IMG=`ls images/ | grep updater | grep zip | grep pi$VERSION | tail -1`
 sshpass -p "$PASSWORD" scp -P $PORT images/$IMG root@$HOST:/data/updater.zip;

 echo "Extracting software on $HOST"
 if [ "$NOREBOOT" == "" ]; then
  sshpass -p "$PASSWORD" ssh -p $PORT root@$HOST /opt/ppos/bin/extract-update --reboot
 else
  sshpass -p "$PASSWORD" ssh -p $PORT root@$HOST /opt/ppos/bin/extract-update
  echo "Not rebooting the system"
 fi

else
 echo "Raspberry Pi version do not match: local $VERSION != remote $REMOTEVERSION"
fi

